### ISSUE TITLE
[feat] tabBar 제작

### ISSUE THREAD

**Issue by Minchelin42** [TEAM-ALOM/fromto-iOS#9]
## 👀 Issue

- bottomSheetView에 tabBar 추가

### ✅ Todo
- [x] Figma에 나온 5가지 항목 tabBar 제작
- [x] Figma 디자인에 맞게 tabBar 제작
- [x] func 이용해서 코드 단순화
